talesarena/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from services.views import Contact, Summary, Services, About
from adverts.views import email_list_signup
from tales.views import (PostListView, PostDetailView, PostCreateView,PostUpdateView, ProfileCreateView, 
                     IndexView, ProfileDetailView,ProfileUpdatelView, ProfileDeleteView, Search, PostDeleteView, 
							like_post, CatSearch, update_profile
							# homePage,
                            )





urlpatterns = [
    url(r'^', include('favicon.urls')),
	path('', IndexView.as_view(), name='home'),
    #path('', homePage, name='home'),
    path('createpost/', PostCreateView.as_view(), name='post-create'),     
    path('post/', PostListView.as_view(), name='post-list'),     
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('victory101/', admin.site.urls),
   
        
]

urlpatterns += [   
    path('profile/<pk>/', ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/<pk>/delete/', ProfileDeleteView.as_view(), name = 'delete-profile'),   
    # path('profile/<pk>/update/',ProfileUpdatelView.as_view(), name = 'update-profile'),   
    path('profile/<pk>/update/', update_profile, name = 'update-profile'),   
]

urlpatterns += [
    url(r'^like/$', like_post, name ="like_post"),
   

]

urlpatterns += [
    path('search/', Search.as_view(), name = 'search'),
    path('catsearch/', CatSearch.as_view(), name = 'catsearch'),
]


urlpatterns += [    
    path('about/', About, name='about'),
    path('contact/', Contact, name='contact'),
    path('summarizer/', Summary, name='summarizer'),
    path('services/',Services, name='services'),
   
]



urlpatterns += [
	path('email-signup/',email_list_signup, name='email-list-signup'),
]


urlpatterns += [
    path('tinymce/', include('tinymce.urls')),
    # url(r'^admin/filebrowser/', include(site.urls)),
]


urlpatterns += [
    path('accounts/', include('allauth.urls')),
    path('account/', include('allauth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace="social")),
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

from django.views.static import serve
urlpatterns += [
url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

tales/forms.py
from django import forms
from tinymce import TinyMCE
import datetime
from .models import Post, Post_Comment, Profile, Category
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
User = get_user_model()
from allauth.account.adapter import DefaultAccountAdapter
from django.forms import ValidationError
from allauth.account.forms import SignupForm
from django.forms import CheckboxInput, HiddenInput
from djangoeditorwidgets.widgets import TinymceWidget


def get_author(user):
    qs = Profile.objects.filter(user=user)
    if qs.exists():
        return qs[0]
    return None
def author(request): 
    author = get_author(request.user)   
    return author

Gender_CHOICE = [   
        ('Male', 'Male'),
        ('Female', 'Female'),    
        ]


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name', widget=forms.TextInput({'placeholder':'First Name','class':'form-class'}))    
    last_name = forms.CharField(max_length=30, label='Last Name', widget=forms.TextInput({'placeholder':'Last Name','class':'form-class'}))    
    # Gender = forms.CharField(required = True, label='Gender', widget=forms.Select(choices=Gender_CHOICE))
    # Birthday = forms.DateField(label='Birthday', widget=forms.SelectDateWidget)
    # Phone_number = forms.IntegerField(required = True, help_text = '',  label='Phone') 
    class Meta:
        model = User 
        fields = '__all__'
    def signup(self, request, user): 
        # user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']      
        user.last_name = self.cleaned_data['last_name']
        # user.Gender = self.cleaned_data['Gender']
        # user.Birthday = self.cleaned_data['Birthday']
        # user.Phone_number = self.cleaned_data['Phone_number']       
        user.save()
        return user


class RestrictEmailAdapter(DefaultAccountAdapter):
    def clean_email(self,email):
        RestrictedList = [' ']
        if email in RestrictedList:
            raise ValidationError('You are restricted from registering. Please contact admin.')
        return email

class URLInput(forms.TextInput):
    input_type = 'url'

class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    title = forms.CharField(required=True, max_length=50, widget=forms.TextInput({
                                                                    'placeholder':'your title',
                                                                    'class' : 'form-control',
                                                                    'maxlength':"50",
                                                                    
                                                                                }))
    overview = forms.CharField(required=True, min_length=750, help_text = 'min-Words:750',
                                                         label="Inspire The World!", 
                                                         widget=forms.Textarea(attrs={
                                                            'class': 'form-control',
                                                            # 'placeholder': 'Your Content',
                                                            'id': '',                                                   
                                                            'border': '2px solid #750a20',
                                                            'cols': 50,
                                                            'rows': 10                                                           
                                                        }))
    # content = forms.CharField(required=False, help_text ='Media Content', label="Get Unique Go Dynamic! ",
    #     widget=TinymceWidget(
    #         attrs={'class': 'form-control', 'cols': 50,'rows': 10 }
    #     )
    # )  
    content = forms.CharField(required=False,
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )
    other_categories =  forms.CharField(max_length=50, required=False,
                                        widget=forms.TextInput({'placeholder':'Add Here, If Your Category is not Listed',
                                                                'class':"form-control",
                                                                 'id':"id_other_categories" 
                                        }))
    # categories = forms.CharField(required = True, label='choose language', widget=forms.Select(choices=Cat_Choice))
    thumbnail = forms.ImageField(required=False, label='Caption Your Content')
    publish =  forms.BooleanField(label='',
                                widget=forms.CheckboxInput(attrs={'class': 'hidden',
                                                                'value': False}), 
                                required=False, 
                                initial=False
                            )

    class Meta:
        model = Post
        fields = ('author','title', 'overview', 'content', 'thumbnail', 
        'categories', 'publish')
        widgets = {
            'content': TinymceWidget()
        }
    

        

        
class CatForm(forms.ModelForm):
    category = forms.CharField(max_length=100, label="Other categories", widget=forms.TextInput({'placeholder':'If Category is not listed'}))
    class Meta:
        model = Category
        fields = ('category',)



class CommentForm(forms.ModelForm):  
    content = forms.CharField( label="Say Something", widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your comment',
        'id': 'usercomment',
        'rows': '4',
        'border': '2px solid #750a20'

    }))
    class Meta:
        model = Post_Comment
        fields = ('content', )
  

        
        
        
     
 
class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=30, label='username', widget=forms.TextInput({'placeholder':'UserName','class': 'form-control'})) 
    email = forms.EmailField( widget=forms.EmailInput({'placeholder':'E-Mail','class': 'form-control'}))
    
    class Meta:
        model = User
        fields = ['username', 'email']


Gender_CHOICE = [   
        ('Gender', 'Gender'),
        ('Male', 'Male'),
        ('Female', 'Female'),    
        ]
from django.forms import ModelForm, DateInput

class DatePickerForm(DateInput):
    input_type = 'date'

class DateInput(forms.DateInput):
    input_type = 'date'

class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, label="first_name", widget=forms.TextInput({'placeholder':'first_name','class': 'form-control'}))
    last_name = forms.CharField(max_length=100, label="last_name", widget=forms.TextInput({'placeholder':'last_name','class': 'form-control'}))
    Gender = forms.CharField(label='Gender', widget=forms.Select(choices=Gender_CHOICE))
    Birthday =  forms.DateField(required = False, label='Birthday',
        widget=forms.DateInput( format='%Y-%m-%d', attrs={'class': 'form-control vDateField', 'type':'Date'}),
        input_formats=['%Y-%m-%d',]
        ) 
   
    bio = forms.CharField(required = False, help_text = 'Tell us SomeThing about YourSelf. (word limit <300', widget=forms.Textarea(attrs={                                                                                          
                                                                                            'class': 'form-control',
                                                                                            'placeholder': 'Your Bio',
                                                                                            'id': 'id_bio',                                                   
                                                                                            'border': '2px solid #750a20',
                                                                                            'cols': 50,
                                                                                            'rows': 10  
                                                                                             }))
    phone_number = forms.IntegerField(required =True,  help_text = "Whatsapp",  widget=forms.NumberInput(attrs={'class': 'form-control'}))
    facebook = forms.URLField(required = False,  help_text = "", widget=URLInput(attrs={'placeholder': 'https://www.facebook.com/your-facebook-id','class': 'form-control'}))
    twitter = forms.URLField(required = False,  help_text = "",  widget=URLInput(attrs={'placeholder': 'https://www.twitter.com/your-twitter-id','class': 'form-control'}))
    instagram = forms.URLField(required = False,  help_text = "",  widget=URLInput(attrs={'placeholder': 'https://www.instagram.com/your-instagram-id','class': 'form-control'}))
    linkedin = forms.URLField(required = False,  help_text = "",  widget=URLInput(attrs={'placeholder': 'https://www.linkedin.com/your-linkedin-id','class': 'form-control'}))
    
 
   

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name','Gender', 'Birthday', 
                  'bio', 'profile_photo',  'phone_number',
                  'linkedin','facebook','twitter','instagram']
        
class ProfileUpdateForm(forms.ModelForm):
    pass
    # first_name = forms.CharField(max_length=100, label="Full Names", widget=forms.TextInput({'placeholder':'Full Names'}))
    # last_name = forms.CharField(max_length=100, label="Full Names", widget=forms.TextInput({'placeholder':'Full Names'}))    

templates/profile/create_profile - Copy.html
{% extends 'base/generic_base.html' %} 
{% load crispy_forms_tags %}
{% load static %}
{% block content %} 


<div class="container set-pad">       
        <div class="col-lg-12">
      <center><h1>Profile Update </h1></center>                   
            
            {{form.media }}
            <form method="POST" action="." enctype="multipart/form-data" class="well form-horizontal">
                {% csrf_token %}
                <fieldset> 
                        {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field }}                    
                      {% endfor %}
                    
                      {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                          {% for error in form.non_field_errors %}
                            {{ error }}
                          {% endfor %}
                        </div>
                      {% endif %}
                        <div class="form-group">
                                {% if u_form.username.errors %}<div class="alert alert-danger" role="alert">{{u_form.username.errors }}</div> {%endif%}
                                {% if u_form.email.errors %}<div class="alert alert-danger" role="alert">{{u_form.email.errors }}</div> {%endif%}   
                                <label class="pull-left control-label"></label>
                                <div class="col-md-10  inputGroupContainer">
                                <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                {{u_form.username}}
                                <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                                {{u_form.email}}                                   
                            </div>
                                </div>
                         </div>
                         
                         <div class="form-group">
                                {% if p_form.first_name.errors %}<div class="alert alert-danger" role="alert">{{u_form.first_name.errors }}</div> {%endif%}
                                {% if p_form.last_name.errors %}<div class="alert alert-danger" role="alert">{{u_form.last_name.errors }}</div> {%endif%}
                                <label class="pull-left control-label"></label>
                                <div class="col-md-10  inputGroupContainer">
                                <div class="input-group">
                                <span class="input-group-addon">First Name</span>
                                    {{p_form.first_name}}
                                <span class="input-group-addon">Last Name</span>
                                     {{p_form.last_name }}                              
                            </div>                                    
                                </div>
                         </div>
                         
                         <div class="form-group">
                                {% if p_form.Gender.errors %}<div class="alert alert-danger" role="alert">{{u_form.Gender.errors }}</div> {%endif%}
                                {% if p_form.Birthday.errors %}<div class="alert alert-danger" role="alert">{{u_form.Birthday.errors }}</div> {%endif%}
                                <label class="pull-left control-label"></label>
                                <div class="col-md-10 inputGroupContainer">
                                <div class="input-group">
                                <span class="input-group-addon"><i class=" fa fa-intersex"></i></span>
                                <select name="Gender" class="select form-control" id="id_Gender">
                                    {%if obj.Gender %}
                                        <option value="{{ obj.Gender}}" selected="">{{ obj.Gender}}</option>
                                    {% endif %}
                                        <option value="Gender">Gender</option>
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>
                                </select>
                                <span class="input-group-addon"><i class="fa fa-calendar-o"> DOB </i></span>
                               {%if obj.Birthday %} 
                                <input  name="Birthday_month"  value="{{ obj.Birthday|date:'Y-m-d'}}" placeholder="Date of Birth"  class="form-control"  type="Date"  required />
                                {% else %} 
                                <input  name="Birthday_month"   placeholder="Date of Birth"  class="form-control"  type="Date"  required />
                                {% endif %}                     
                                    </div>
                                </div>
                         </div>
                         <div class="container">
                                <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                    <label class="pull-left control-label"></label>
                                                    <div class="inputGroupContainer">
                                                    <div class="input-group">
                                               <p> <span class="input-group-addon"><i class="fa fa-info-circle"> Your Bio </i></span>
                                               <small> <i class="alert-danger" role="alert" id="warn"> </i></small>
                                                {% if obj.bio %}
                                                <textarea name="bio" cols="40" rows="3" class="textarea form-control" required id="id_bio">
                                                        {{obj.bio}}
                                                </textarea>  </p>                 
                                                    {% else %}
                                                    <textarea name="bio" cols="40" rows="3" onkeyup="if (this.value.length > 300 ) { alert('bio word limit is 300'); return false; }" class="textarea form-control" required id="id_bio">
                                                    </textarea>                                
                                                    {% endif %}
                                            
                                                    </div>
                                                    <small id="hint_id_bio" class="form-text text-muted">Tell us Something about You.(words limit 300)</small>
                                            </div>
                                            </div>
                                        </div>
                    <div class="col-md-6">
                         <div class="form-group">                                
                                <div class="col-md-offset-1 inputGroupContainer">
                                 <label class="pull-left control-label">Profile Photo</label>
                                <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-image"></i></span>
                                <span>
                          {% if obj.profile_photo %}
                                Currently: <a href="{{ obj.profile_photo.url }}">{{ obj.profile_photo }}</a>
                                <input type="checkbox" name="profile_photo-clear" id="profile_photo-clear_id">  
                                <label for="profile_photo-clear_id">Clear</label><br>  
                                <input type="file" name="profile_photo" accept="image/*" class="clearablefileinput" id="id_profile_photo">                                                                    
                                {% else %} 
                                <input type="file" name="profile_photo" accept="image/*" class="clearablefileinput" id="id_profile_photo">                               
                                {% endif %} 
                            </span>                                 
                                    </div>
                                </div>
                         </div>
                        </div>
                    </div>
               </div>                      
                         <div class="form-group">                                
                                <div class="col-md-12 inputGroupContainer">
                                <label class="pull-left control-label">Social Connects</label>
                                <div class="input-group">
                          
                                <span class="input-group-addon"><i class="fa fa-whatsapp"></i></span>
                                {% if obj.phone_number %}   
                                <input type="text" name="phone_number" value="{{obj.phone_number}}" placeholder="Phone Number" maxlength="100" class="textinput textInput form-control" id="id_phone_number">
                                {% else %} 
                                <input type="text" name="phone_number" placeholder="Phone Number" maxlength="100" class="textinput textInput form-control" id="id_phone_number">
                                {% endif %} 
                                
                                <span class="input-group-addon"><i class="fa fa-facebook"></i></span>
                                {% if  obj.facebook %}   
                                <input type="url" name="facebook" value="{{ obj.facebook}}" placeholder="https://www.facebook.com/your-facebook-id" class="urlinput form-control" id="id_facebook">
                                {% else %} 
                                <input type="url" name="facebook" placeholder="https://www.facebook.com/your-facebook-id" class="urlinput form-control" id="id_facebook">
                                {% endif %} 
                                
                                <span class="input-group-addon"><i class="fa fa-twitter"></i></span>
                                {% if  obj.twitter %}   
                                <input type="url" name="twitter" value="{{obj.twitter}}" placeholder="https://www.twitter.com/your-twitter-id" class="urlinput form-control" id="id_twitter"> 
                                {% else %} 
                                <input type="url" name="twitter" placeholder="https://www.twitter.com/your-twitter-id" class="urlinput form-control" id="id_twitter"> 
                                {% endif %} 
                                
                                <span class="input-group-addon"><i class="fa fa-instagram"></i></span>
                                {% if obj.instagram %}   
                                <input type="url" name="instagram" value="{{obj.instagram}}" placeholder="https://www.instagram.com/your-instagram-id" class="urlinput form-control" id="id_instagram">
                                {% else %} 
                                <input type="url" name="instagram" placeholder="https://www.instagram.com/your-instagram-id" class="urlinput form-control" id="id_instagram">
                                {% endif %}
                               
                                <span class="input-group-addon"><i class="fa fa-linkedin"></i></span>
                                {% if obj.linkedin %}   
                                <input type="url" name="linkedin" value="{{obj.linkedin}}" placeholder="https://www.linkedin.com/your-linkedin-id" class="urlinput form-control" id="id_linkedin">
                                {% else %} 
                                <input type="url" name="linkedin"  placeholder="https://www.linkedin.com/your-linkedin-id" class="urlinput form-control" id="id_linkedin">
                                {% endif %}
                            
                                    </div>
                                </div>
                         </div>

              
                      
                </fieldset>
                <center><button name="profile" class="btn btn-primary btn-sm" type="submit">Submit</button> </center>
            </form><br>            
    </div>
</div>

{% endblock content %}

templates/profile/profile_confirm_delete.html
{% extends 'base/generic_base.html' %} 
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

  <center class="container top10 bottom10">
      <div class="row top2 bottom2">       
        <main class=""> 
          <div class="container">
            <p class="h3"><b>{{ object }}! </b>Are you sure you want to delete Your Account?</p>
            <form method="post">
                {% csrf_token %} 
           
         	<a href="/profile/{{ request.user.profile.pk }}" class="btn btn-info">No</a>
         	            &emsp;&emsp;&emsp;&emsp;               
              <input class="btn btn-danger" type="submit" value="Yes"> 
          	
            </form>
           
          </div>
        </main>               
      </div>
    </center>
{% endblock%}

templates/profile/profile_form.html
{% extends 'base/generic_base.html' %} 
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

 {% if request.user.is_authenticated %}
<div class="container set-pad well" style="background-color: #a5d5dabf; border: 21x solid #152c35;">       
    <div class="col-lg-12">
      <center><h1>{{ mytitle }}</h1></center>                  
            
            {{ form.media }}
            <form method="POST" action="." enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form|crispy }}
                {{ form_class|crispy }}
               
                
                
                <center><button class="btn btn-primary btn-sm" type="submit">Submit</button></center>
            </form><br>           
    </div>
</div>

{% else %}
<hr>   
<center class="top10" style="position:relative; padding-bottom: 17vw; bottom: 0">
    <p class="h3"> Login To Access This Page</p>    
    <a href="{% url 'account_login' %}?next={{request.path}}" class="btn btn-primary">login</a>
</center><hr>
{% endif %}
{% endblock content %}