talesarena/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from services.views import Contact, Summary, Services, About
from adverts.views import email_list_signup
from tales.views import (PostListView, PostDetailView, PostCreateView,PostUpdateView, ProfileCreateView, 
                     IndexView, ProfileDetailView,ProfileUpdatelView, ProfileDeleteView, Search, PostDeleteView, 
							like_post, CatSearch, update_profile
							# homePage,
                            )





urlpatterns = [
    url(r'^', include('favicon.urls')),
	path('', IndexView.as_view(), name='home'),
    #path('', homePage, name='home'),
    path('createpost/', PostCreateView.as_view(), name='post-create'),     
    path('post/', PostListView.as_view(), name='post-list'),     
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('victory101/', admin.site.urls),
   
        
]

urlpatterns += [   
    path('profile/<pk>/', ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/<pk>/delete/', ProfileDeleteView.as_view(), name = 'delete-profile'),   
    # path('profile/<pk>/update/',ProfileUpdatelView.as_view(), name = 'update-profile'),   
    path('profile/<pk>/update/', update_profile, name = 'update-profile'),   
]

urlpatterns += [
    url(r'^like/$', like_post, name ="like_post"),
   

]

urlpatterns += [
    path('search/', Search.as_view(), name = 'search'),
    path('catsearch/', CatSearch.as_view(), name = 'catsearch'),
]


urlpatterns += [    
    path('about/', About, name='about'),
    path('contact/', Contact, name='contact'),
    path('summarizer/', Summary, name='summarizer'),
    path('services/',Services, name='services'),
   
]



urlpatterns += [
	path('email-signup/',email_list_signup, name='email-list-signup'),
]


urlpatterns += [
    path('tinymce/', include('tinymce.urls')),
    # url(r'^admin/filebrowser/', include(site.urls)),
]


urlpatterns += [
    path('accounts/', include('allauth.urls')),
    path('account/', include('allauth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace="social")),
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

from django.views.static import serve
urlpatterns += [
url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

tales/models.py
from tinymce import HTMLField
from django.db import models
from allauth.account.signals import user_signed_up
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
User = get_user_model()
from django_resized import ResizedImageField
from djangoeditorwidgets.fields import XMLField

class PostView(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    post = models.ForeignKey('Post', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

Gender_CHOICE = [   
        ('Male', 'Male'),
        ('Female', 'Female'),    
        ]
 
class Profile(models.Model):   
    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)   
    first_name = models.CharField(max_length=20, blank=True, null=True)
    last_name = models.CharField(max_length=20, blank=True, null=True)
    Gender = models.CharField(max_length=10, choices=Gender_CHOICE, help_text='Gender', blank=True, null=True)
    Birthday = models.DateField(blank=True, null=True)
    profile_photo = ResizedImageField(size=[215, 215], upload_to='profile', blank=True, null=True)   
    bio = models.TextField(blank=True, null=True)
    phone_number = models.CharField(help_text = 'phone number',max_length=20, blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    twitter= models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)     

    def get_absolute_url(self):
        return reverse('profile-detail', kwargs={
            'pk': self.pk
        })

    def __str__(self): 
        return self.user.username


class Category(models.Model):
    category = models.CharField(max_length=20)
    def __str__(self):
        return self.category

def ProfileCallback(sender, request, user, **kwargs):
    userProfile, is_created = Profile.objects.get_or_create(user=user)
    if is_created:
        # userProfile.user = user.username
        userProfile.first_name = user.first_name
        userProfile.last_name = user.last_name        
        
        # userProfile.Birthday = user.Birthday
        # userProfile.phone_number = user.phone_number 
        userProfile.save()
user_signed_up.connect(ProfileCallback)



class Post_Comment(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=1000)
    # image = models.CharField(max_length=100000000)
    image = models.ImageField(default='')
    link = models.CharField(max_length=100, default="'profile/'+request.user", blank=True, null=True)
    post = models.ForeignKey(
        'Post', related_name='comments', on_delete=models.CASCADE)    

    def __str__(self):
        return self.user.username

class Postsum(models.Model):
    pass 
  
    

class Post(models.Model): 
    title = models.CharField(max_length=100)   
    timestamp = models.DateTimeField(auto_now_add=True)
    overview = models.TextField()
    content = HTMLField(blank=True, null=True)   #or XMLField()    
    author = models.ForeignKey('Profile', on_delete=models.SET_NULL, null=True)
    thumbnail = ResizedImageField(size=[820, 420], upload_to='post', blank=True, null=True, force_format='PNG')
    categories = models.ManyToManyField(Category, blank=True)
    other_categories = models.CharField(max_length=50, blank=True, null=True)
    publish = models.BooleanField( default = False)
    likes = models.ManyToManyField(User, related_name='likes', blank= True)  
    previous_post = models.ForeignKey(
        'self', related_name='previous', on_delete=models.SET_NULL, blank=True, null=True)
    next_post = models.ForeignKey(
        'self', related_name='next', on_delete=models.SET_NULL, blank=True, null=True)
    
    class Meta:
        app_label = 'tales'
    def get_cropping_as_list(self):
        if self.cropping:
            return list(map(int, self.cropping.split(',')))

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={
            'pk': self.pk
        })
   
    def __str__(self):
        return self.title

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def comment_count(self):
        return Post_Comment.objects.filter(post=self).count()

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

    @property
    def total_likes(self):
        return self.likes.count()

   



    



   

tales/forms.py
from django import forms
from tinymce import TinyMCE
import datetime
from .models import Post, Post_Comment, Profile, Category
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
User = get_user_model()
from allauth.account.adapter import DefaultAccountAdapter
from django.forms import ValidationError
from allauth.account.forms import SignupForm
from django.forms import CheckboxInput, HiddenInput
from djangoeditorwidgets.widgets import TinymceWidget


def get_author(user):
    qs = Profile.objects.filter(user=user)
    if qs.exists():
        return qs[0]
    return None
def author(request): 
    author = get_author(request.user)   
    return author

Gender_CHOICE = [   
        ('Male', 'Male'),
        ('Female', 'Female'),    
        ]


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name', widget=forms.TextInput({'placeholder':'First Name','class':'form-class'}))    
    last_name = forms.CharField(max_length=30, label='Last Name', widget=forms.TextInput({'placeholder':'Last Name','class':'form-class'}))    
    # Gender = forms.CharField(required = True, label='Gender', widget=forms.Select(choices=Gender_CHOICE))
    # Birthday = forms.DateField(label='Birthday', widget=forms.SelectDateWidget)
    # Phone_number = forms.IntegerField(required = True, help_text = '',  label='Phone') 
    class Meta:
        model = User 
        fields = '__all__'
    def signup(self, request, user): 
        # user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']      
        user.last_name = self.cleaned_data['last_name']
        # user.Gender = self.cleaned_data['Gender']
        # user.Birthday = self.cleaned_data['Birthday']
        # user.Phone_number = self.cleaned_data['Phone_number']       
        user.save()
        return user


class RestrictEmailAdapter(DefaultAccountAdapter):
    def clean_email(self,email):
        RestrictedList = [' ']
        if email in RestrictedList:
            raise ValidationError('You are restricted from registering. Please contact admin.')
        return email

class URLInput(forms.TextInput):
    input_type = 'url'

class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    title = forms.CharField(required=True, max_length=50, widget=forms.TextInput({
                                                                    'placeholder':'your title',
                                                                    'class' : 'form-control',
                                                                    'maxlength':"50",
                                                                    
                                                                                }))
    overview = forms.CharField(required=True, min_length=750, help_text = 'min-Words:750',
                                                         label="Inspire The World!", 
                                                         widget=forms.Textarea(attrs={
                                                            'class': 'form-control',
                                                            # 'placeholder': 'Your Content',
                                                            'id': '',                                                   
                                                            'border': '2px solid #750a20',
                                                            'cols': 50,
                                                            'rows': 10                                                           
                                                        }))
    # content = forms.CharField(required=False, help_text ='Media Content', label="Get Unique Go Dynamic! ",
    #     widget=TinymceWidget(
    #         attrs={'class': 'form-control', 'cols': 50,'rows': 10 }
    #     )
    # )  
    content = forms.CharField(required=False,
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )
    other_categories =  forms.CharField(max_length=50, required=False,
                                        widget=forms.TextInput({'placeholder':'Add Here, If Your Category is not Listed',
                                                                'class':"form-control",
                                                                 'id':"id_other_categories" 
                                        }))
    # categories = forms.CharField(required = True, label='choose language', widget=forms.Select(choices=Cat_Choice))
    thumbnail = forms.ImageField(required=False, label='Caption Your Content')
    publish =  forms.BooleanField(label='',
                                widget=forms.CheckboxInput(attrs={'class': 'hidden',
                                                                'value': False}), 
                                required=False, 
                                initial=False
                            )

    class Meta:
        model = Post
        fields = ('author','title', 'overview', 'content', 'thumbnail', 
        'categories', 'publish')
        widgets = {
            'content': TinymceWidget()
        }
    

        

        
class CatForm(forms.ModelForm):
    category = forms.CharField(max_length=100, label="Other categories", widget=forms.TextInput({'placeholder':'If Category is not listed'}))
    class Meta:
        model = Category
        fields = ('category',)



class CommentForm(forms.ModelForm):  
    content = forms.CharField( label="Say Something", widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your comment',
        'id': 'usercomment',
        'rows': '4',
        'border': '2px solid #750a20'

    }))
    class Meta:
        model = Post_Comment
        fields = ('content', )
  

        
        
        
     
 
class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=30, label='username', widget=forms.TextInput({'placeholder':'UserName','class': 'form-control'})) 
    email = forms.EmailField( widget=forms.EmailInput({'placeholder':'E-Mail','class': 'form-control'}))
    
    class Meta:
        model = User
        fields = ['username', 'email']


Gender_CHOICE = [   
        ('Gender', 'Gender'),
        ('Male', 'Male'),
        ('Female', 'Female'),    
        ]
from django.forms import ModelForm, DateInput

class DatePickerForm(DateInput):
    input_type = 'date'

class DateInput(forms.DateInput):
    input_type = 'date'

class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, label="first_name", widget=forms.TextInput({'placeholder':'first_name','class': 'form-control'}))
    last_name = forms.CharField(max_length=100, label="last_name", widget=forms.TextInput({'placeholder':'last_name','class': 'form-control'}))
    Gender = forms.CharField(label='Gender', widget=forms.Select(choices=Gender_CHOICE))
    Birthday =  forms.DateField(required = False, label='Birthday',
        widget=forms.DateInput( format='%Y-%m-%d', attrs={'class': 'form-control vDateField', 'type':'Date'}),
        input_formats=['%Y-%m-%d',]
        ) 
   
    bio = forms.CharField(required = False, help_text = 'Tell us SomeThing about YourSelf. (word limit <300', widget=forms.Textarea(attrs={                                                                                          
                                                                                            'class': 'form-control',
                                                                                            'placeholder': 'Your Bio',
                                                                                            'id': 'id_bio',                                                   
                                                                                            'border': '2px solid #750a20',
                                                                                            'cols': 50,
                                                                                            'rows': 10  
                                                                                             }))
    phone_number = forms.IntegerField(required =True,  help_text = "Whatsapp",  widget=forms.NumberInput(attrs={'class': 'form-control'}))
    facebook = forms.URLField(required = False,  help_text = "", widget=URLInput(attrs={'placeholder': 'https://www.facebook.com/your-facebook-id','class': 'form-control'}))
    twitter = forms.URLField(required = False,  help_text = "",  widget=URLInput(attrs={'placeholder': 'https://www.twitter.com/your-twitter-id','class': 'form-control'}))
    instagram = forms.URLField(required = False,  help_text = "",  widget=URLInput(attrs={'placeholder': 'https://www.instagram.com/your-instagram-id','class': 'form-control'}))
    linkedin = forms.URLField(required = False,  help_text = "",  widget=URLInput(attrs={'placeholder': 'https://www.linkedin.com/your-linkedin-id','class': 'form-control'}))
    
 
   

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name','Gender', 'Birthday', 
                  'bio', 'profile_photo',  'phone_number',
                  'linkedin','facebook','twitter','instagram']
        
class ProfileUpdateForm(forms.ModelForm):
    pass
    # first_name = forms.CharField(max_length=100, label="Full Names", widget=forms.TextInput({'placeholder':'Full Names'}))
    # last_name = forms.CharField(max_length=100, label="Full Names", widget=forms.TextInput({'placeholder':'Full Names'}))    

templates/post_form.html
{% extends 'base/generic_base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}
{% if request.user.profile.user %}
<p class="text-center h2 top2">{{ mytitle }}</p>
<p class="text-center h4 top2"><em>{{ subtitle }}</em></p>

<section class="container top3"> 
    <div class="row">            
        <div class="col-lg-12">
                <center><a href="/about/#tips" class="text-center">CheckOut These Tips For creating Award Winning Tales</a></center>    
            <div class="">               
                {{ form.media }}
                <form method="POST" action="." enctype="multipart/form-data" class="well form-horizontal">
                   <fieldset> 
                    {% for hidden_field in form.hidden_fields %}
                      {{ hidden_field }}
                    {% endfor %}
                  
                    {% if form.non_field_errors %}
                      <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                          {{ error }}
                        {% endfor %}
                      </div>
                    {% endif %}
                    {% csrf_token %}                      
                            
                    
                    <div class="form-group">
                            {%if form.title.errors %}<div class="alert alert-danger" role="alert">{{ form.title.errors }}</div> {%endif%}                            
                            <label class="pull-left control-label">{{ form.title.label_tag }}*</label>
                            <div class="col-md-6 inputGroupContainer">
                            <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-info-circle"></i></span>
                             {{ form.title }}                            
                              </div>
                            </div>
                        </div>
                       <div class="form-group">
                            {%if form.content.errors %}<div class="alert alert-danger" role="alert">{{ form.content.errors }}</div> {%endif%}                            
                            <label class="pull-left control-label">{{ form.content.label_tag }}*</label>
                                <div class="col-md-12 inputGroupContainer">
                                    <div class="input-group">
                                    <p>
                                       <span class="input-group-addon"><i class=" fa fa-align-center"></i></span>
                                        {{ form.content }}     
                                    </p>                       
                                    </div>
                                    {% if form.content.help_text %}
                                    <small class="form-text text-muted">{{form.content.help_text }}</small>
                                    {% endif %}
                                </div>
                         </div>
                         {%if form.media_content.errors %}<div class="alert alert-danger" role="alert">{{ form.media_content.errors }}</div> {%endif%} 
                   <details>
                       <summary class="text-info">{{ form.media_content.label_tag }} </summary>
                             <div class="form-group">                                
                                    <label class="pull-left control-label"></label>
                                    <div class="col-md-12 inputGroupContainer">
                                        <div class="input-group">
                                            <p>
                                                 <span class="input-group-addon"><i class=" fa fa-align-center"></i></span>
                                                {{ form.media_content }} 
                                            </p>
                                            <script type="text/javascript">
                                                (function($){function tinymce4_init(selector){var tinymce4_config={setup:function(editor){editor.on('change',function(){editor.save();});},"cleanup_on_startup":true,"custom_undo_redo_levels":20,"selector":"textarea#id_content","theme":"modern","plugins":"\n            textcolor save link image media preview codesample contextmenu\n            table code lists fullscreen  insertdatetime  nonbreaking\n            contextmenu directionality searchreplace wordcount visualblocks\n            visualchars code fullscreen autolink lists  charmap print  hr\n            anchor pagebreak\n            ","toolbar1":"\n            fullscreen preview bold italic underline | fontselect,\n            fontsizeselect  | forecolor backcolor | alignleft alignright |\n            aligncenter alignjustify | indent outdent | bullist numlist table |\n            | link image media | codesample |\n            ","toolbar2":"\n            visualblocks visualchars |\n            charmap hr pagebreak nonbreaking anchor |  code |\n            ","contextmenu":"formats | link image","menubar":true,"statusbar":true,"language":"en","directionality":"ltr"};if(typeof selector!='undefined'){tinymce4_config['selector']=selector;}
                                                tinymce.init(tinymce4_config);}
                                                tinymce4_init();})();
                                            </script>
                                        </div>
                                        {% if form.media_content.help_text %}
                                        <small class="form-text text-muted">{{ form.media_content.help_text }}</small>
                                        {% endif %}
                                    </div>
                             </div>
                    </details>         <br>

                             <div class="form-group">
                                    {%if form.thumbnail.errors %}<div class="alert alert-danger" role="alert">{{ form.thumbnail.errors }}</div> {%endif%} 
                                    <label class="pull-left control-label">{{ form.thumbnail.label_tag }}</label>
                                    <div class="col-md-8 inputGroupContainer">
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-image"></i></span>
                                            <span>
                                                {% if thumbnail %}
                                                Currently: <a href="{{thumbnail.url}}">{{thumbnail}}</a>
                                                <input type="checkbox" name="thumbnail-clear" id="thumbnail-clear_id">  
                                                <label for="thumbnail-clear_id">Clear</label><br>                                                                                
                                                {{ form.thumbnail }} 
                                                {% else %} 
                                                {{ form.thumbnail }}                                   
                                                {% endif %} 
                                            </span>                                 
                                        </div>
                                    </div>
                             </div>
                             <div class="form-group">
                                    {%if form.categories.errors %}<div class="alert alert-danger" role="alert">{{ form.categories.errors }}</div> {%endif%}
                                    {%if form.other_categories.errors %}<div class="alert alert-danger" role="alert">{{ form.other_categories.errors }}</div> {%endif%}
                                    <label class="pull-left control-label">{{ form.categories.label_tag }}</label>
                                    <div class="col-md-6 inputGroupContainer">
                                    <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-list"></i></span>
                                    <select name="categories" value="{{categories}}" class="selectmultiple form-control" id="id_categories" multiple>                                        
                                    {% if categories %}
                                        {% for cate in categories.all %}
                                        <option value="{{ forloop.counter }}" selected="">{{cate}}</option>
                                     {% endfor %}
                                    {% endif %}
                                    {% for cat in category %}
                                            <option value="{{ forloop.counter }}">{{cat}}</option>
                                    {% endfor %}
                                    </select>
                                {% if other_categories %}
                                    <input type="text" name="other_categories" value="{{other_categories}}" placeholder="if category is not listed" maxlength="50" class="textinput textInput form-control" id="id_other_categories">
                               {% else %}
                               
                                    <input type="text" name="other_categories" placeholder="if category is not listed" maxlength="50" class="textinput textInput form-control" id="id_other_categories">
                                {% endif %} 
                                </div>
                                    </div>
                             </div>
                             <div class="form-group">
                                    <label class="pull-left control-label"></label>
                                    <div class="col-md-6 inputGroupContainer">
                                    <div class="input-group">                                    
                                    <input type="checkbox" name="terms" value="True" required> 
                                    <a href="/about/#terms"> I Accept all Talesarena Publishing Terms and Conditions </a>
                                        </div>
                                    </div>
                             </div> 
                    </fieldset>                    
                    <center><button class="btn btn-primary" type="submit">Submit</button></center>
                </form>
            </div>
        </div>
    </div>
</section>
{% else %}
<center style="position:relative; padding-bottom: 9vw;"><hr>
    {% if request.user.is_authenticated %}
    <p class="h3"> you have to update your profile to create post</p>    
    <a href="/createprofile" class="btn btn-primary">click here to update your profile</a>
    {% else %}
     <p class="h3"> you have to login to access this page</p>    
    <a href="{% url 'account_login' %}?next={{request.path}}" class="btn btn-primary">login</a>
</center><hr>

{% endif %}
{% endif %}
{% endblock content %}